config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  
  get '/dashboard', to: 'users#dashboard'
  get '/users/:id', to: 'users#show'
  get '/selling_orders', to: 'orders#selling_orders'
  get '/buying_orders', to: 'orders#buying_orders'  
  get '/all_requests', to: 'requests#list'

  post '/users/edit', to: "users#update"
  
  put '/orders/:id/complete', to: 'orders#complete', as: 'complete_order'
  
  resources :gigs do
    member do
      delete :delete_photo
      post :upload_photo
    end
    resources :orders, only: [:create] 
  end

  resources :requests

  devise_for :users, 
              path: '',
              path_names: {sign_up: 'register', sign_in: 'login', edit: 'profile', sign_out: 'logout'},
              controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
  belongs_to :category

  has_one_attached :attachement_files

  validates :title, presence: {message: "Cannot be Empty"}
  validates :description, presence: {message: "Cannot be Empty"}
  validates :delivery, numericality: {only_integer: true, message: "Must be a number"}
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_request, except: [:new, :create, :index, :list]
  before_action :is_authorised, only: [:edit, :update, :destroy]
  before_action :set_categories, only: [:new, :edit, :list]
  
  def index
    @requests = current_user.requests
  end

  def new
    @request = current_user.requests.build
  end

  def create
    @request = current_user.requests.build(request_params)
    if @request.save
      redirect_to requests_path, notice: "Saved..."
    else
      redirect_to request.referrer, flash: {error: @requests.errors.full_messages.join(', ')}
    end
  end

  def edit
  end

  def update
    if @request.update(request_params)
      redirect_to requests_path, notice: "Saved..."
    else
      redirect_to request.referrer, flash: {error: @requests.errors.full_messages.join(', ')}
    end
  end

  def show
  end

  def destroy
    @request.destroy
    redirect_to requests_path, notice: "Request Deleted."
  end

  def list
    @category_id = params[:category]
    if @category_id.present? 
      @request = Request.where(category_id: @category_id)
    else
      @request = Request.all
    end

  end


  private

  def set_categories
    @categories = Category.all
  end
  def set_request
    @request= Request.find(params[:id])
    
  end
  
  def is_authorised
  redirect_to root_path, alert: "You dont have permission" unless current_user.id == @request.user_id     
  end
  

  def request_params
    params.require(:request).permit(:description, :category_id, :title,
                                :delivery, :budget, :attachement_files)
    
  end
  
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/edit.html.erb
<section class="container">
    <div class="container">
        <div class="form-container">
            <p class="title is-4 has-text-centered">What services are you looking for?</p>
            <%= form_for @request do |f| %>
              <div class="field">
                <label class="label">Title (*)</label>
                <%= f.text_field :title, placeholder: "I request...", class: "input"%>
              </div>
              <div class="field">
                <label class="label">Description (*)</label>
                <%= f.text_area :description, placeholder: "I request...", class: "textarea"%>
              </div>
              <div class="field">
                <label class="label">Choose a Category</label>
                <div class="select is-fullwidth">
                    <%= f.select(:category_id, options_for_select(@categories.map{ |c| [c.name, c.id] }, selected: @request.category_id))%>
                </div>
              </div>
              <div class="field">
                <label class="label">Delivery</label>
                <%= f.number_field :delivery, placeholder: "1-30 days", class: "input"%>
              </div>
              <div class="field">
                <label class="label">Budget</label>
                <%= f.number_field :budget, placeholder: "$5 minimum", class: "input"%>
              </div>
              <div class="field">
                <label class="label">Upload Attachment (optional)</label>
                <div class="file is-warning has-name">
                    <label class="file-label">
                        <%= f.file_field :attachement_files, class: "file-input"%>
                        <span class="file-cta"><span class="file-label">Choose a file...</span></span>
                        <span class="file-name" id="file-name">No file selected</span>
                    </label>
                </div>
              </div>

              <% if @request.attachement_files.attached? %>
                <%= link_to url_for(@request.attachement_files), 
                    class:"tag small is-warning m-t-20",
                    download: "Attachment_#{@request.attachement_files.id}" do %>
                    <i class= "fas fa-paperclip fa-lg p-r-5"></i> <%= @request.attachement_files.filename%>
                    <%end%>
              <% end %>

              <div class="field has-text-centered">
                <%= f.submit 'Update Request', class: "button is-primary "%>
              </div>
            <% end %>
        </div>
    </div>
</section>

<script>
     $(document).ready(function(){
        var file = $('.file-input');
        file.change(function(e){
            if (file[0].files.length > 0){
                var attachement = file[0].files[0]
                $('.file-name').text(attachement.name + " ("+ attachement.size + " bytes)")
            }
        })
    })
</script>

app/views/requests/index.html.erb
<section class="section">
    <div class="container">
        <p class="title">Manage Request 
            <%= link_to 'Post New Request', new_request_path, class: "button is-primary is-pulled-right" %>
        </p>
        <table class="table is-fullwidth">
            <thead class="is-centered">
                <tr>
                    <td>Date</td>
                    <td>Request</td>
                    <td class="has-text-right">Offers</td>
                    <td class="has-text-right">Action</td>
                </tr>
            </thead>
            <tbody>
                <% if @requests.blank? %>
                <tr>
                    <td colspan="4" class="has-text-centered"><h1>Nothing to show here</h1></td>
                </tr>
                <% end %>

                <% @requests.each do |r| %>
                    <tr>
                        <td><%= r.created_at.strftime('%d, %b %Y')%></td>
                        <td><%= link_to r.title, request_path(r)%></td>
                        <td class="has-text-right">3</td>
                        <td class="has-text-right">
                            <%= link_to edit_request_path(r), class:"m-r-5" do %>
                                <span class="icon has-text-success">
                                    <i class="far fa-edit fa-lg"></i>
                                </span>
                            <%end%>
                            <%= link_to r, method: :delete, data: {confirm: "Are you sure?"} do %>
                                <span class="icon has-text-danger">
                                    <i class="far fa-trash-alt fa-lg"></i>
                                </span>
                            <%end%>
                        </td>
                    </tr>
                <% end %>
            </tbody>
        </table>
    </div>
</section>

app/views/requests/list.html.erb
<section>
    <div class="container"> 
        <p class="title">All Requests</p>
        <%= link_to 'Post a Request', new_request_path, class: "button is-primary is-pulled-right" %>
    </div>
    <div class="card">
        <div class="card-header">
            <%= form_tag '', method: :get do  %>
                <div class="field p-10"> 
                    <div class="select">
                        <%= select_tag 'category', content_tag(:option, "All Categories", value: "")+
                                                    options_for_select(@categories.map {|c| [c.name, c.id]},
                                                    selected: @category_id),
                                                    onchange: "this.form.submit();" %>
                    </div>
                </div>
            <%end%>
        </div>
        <div class="card-content">
            <table class="table is-fullwidth">
            <thead>
               

                <tr>
                    <th>Date</th>
                    <th>Buyer</th>
                    <th>Request</th>
                    <th class="has-text-center">Offers</th>
                    <th class="has-text-center">Duration</th>
                    <th class="has-text-center">Budget</th>
                </tr>
            </thead>
            <tbody>
                <% if @request.blank? %>
                    <tr>
                        <td colspan="6" class="has-text-centered"><h1>Nothing to show here</h1></td>
                    </tr>
                <% end %>
                <% @request.each do |r|%>
                    <tr>
                        <td><%= r.created_at.strftime('%d, %b %Y')%></td>
                        <td>
                            <figure class="image is-48x48">
                                <%= image_tag avatar_url(r.user), class: "is-rounded" %>
                            </figure>
                        </td>
                        <td>
                            <%= link_to request_path(r), class: "tooltip" do %>
                                <label for="" class="tooltip" data-tooltip="<%=r.description %>">
                                    <%= r.title.truncate(25, separator: ' ')%>
                                </label>
                            <%end%>
                        </td>
                        <td class="has-text-right">5</td>
                        <td class="has-text-right"><%= pluralize(r.delivery, 'day') %></td>
                        <td class="has-text-right"><%= r.budget %></td>
                    </tr>
                <%end%>
            </tbody>
            </table>
        </div>
    </div>
</section>

app/views/requests/new.html.erb
<section class="container">
    <div class="container">
        <div class="form-container">
            <p class="title is-4 has-text-centered">What services are you looking for?</p>
            <%= form_for @request do |f| %>
              <div class="field">
                <label class="label">Title (*)</label>
                <%= f.text_field :title, placeholder: "I request...", class: "input"%>
              </div>
              <div class="field">
                <label class="label">Description (*)</label>
                <%= f.text_area :description, placeholder: "I request...", class: "textarea"%>
              </div>
              <div class="field">
                <label class="label">Choose a Category</label>
                <div class="select is-fullwidth">
                    <%= f.select(:category_id, options_for_select(@categories.map{ |c| [c.name, c.id] }))%>
                </div>
              </div>
              <div class="field">
                <label class="label">Delivery</label>
                <%= f.number_field :delivery, placeholder: "1-30 days", class: "input"%>
              </div>
              <div class="field">
                <label class="label">Budget</label>
                <%= f.number_field :budget, placeholder: "$5 minimum", class: "input"%>
              </div>
              <div class="field">
                <label class="label">Upload Attachment (optional)</label>
                <div class="file is-warning has-name">
                    <label class="file-label">
                        <%= f.file_field :attachment_file, class: "file-input"%>
                        <span class="file-cta"><span class="file-label">Choose a file...</span></span>
                        <span class="file-name" id="file-name">No file selected</span>
                    </label>
                </div>
              </div>

              <div class="field has-text-centered">
                <%= f.submit 'Post Request', class: "button is-primary "%>
              </div>
            <% end %>
        </div>
    </div>
</section>

<script>
     $(document).ready(function(){
        var file = $('.file-input');
        file.change(function(e){
            if (file[0].files.length > 0){
                var attachment = file[0].files[0]
                $('.file-name').text(attachment.name + " ("+ attachment.size + " bytes)")
            }
        })
    })
</script>

app/views/requests/show.html.erb
<section class="section">
    <div class="container">
        <div class="columns">

            <!-- LEFT SIDE -->
            <div class="column is-two-thirds">
                <div class="columns is-multiline">

                    <!-- Title -->
                    <div class="column is-full">
                        <p class="title is-4"><%= @request.title %></p>
                        <article class="media">
                            <div class="media-content">
                                <p>
                                    <%= @request.category.name%>
                                    <span class="is-pulled-right">
                                        Posted on <%= @request.created_at.strftime('%d, %b %Y') %>
                                    </span>
                                </p>
                                Need to be delivered in: <%= @request.delivery %> days | Offers 0 | Budget: <%= @request.budget %> 
                            </div>
                        </article>
                    </div>

                    <!-- Description -->
                    <div class="column is-full">
                        <div class="card">
                            <div class="card-content">
                                <strong>Description</strong>
                                <hr>
                                <%= @request.description %>
                                <% if @request.attachement_files.attached? %>
                                    <p>
                                        <%= link_to url_for(@request.attachement_files), 
                                                class:"tag small is-warning m-t-20",
                                                download: "Attachement_#{@request.attachement_files.id}" do %>
                                                <i class="fas fa-paperclip fa-lg p-r-5"></i><%= @request.attachement_files.filename%>
                                        <%end%>
                                    </p>
                                <%end%>
                            </div>
                        </div>
                    </div>

                    <!-- About Buyer -->
                    <div class="column">
                        <div class="card">
                            <div class="card-content">
                                <strong>About the Buyer</strong> 
                                <hr/>

                                <div class="content">
                                    <div class="columns">

                                        <!-- Buyer Avatar -->
                                        <div class="column">
                                            <div class="card-content is-horizontal-center is-flex">
                                                <figure class="image is-96x96">
                                                    <%= image_tag avatar_url(@request.user), class: "is-rounded" %>
                                                </figure>
                                            </div>
                                            <div class="card-content has-text-centered">
                                                <p class="title is-5"><%= @request.user.full_name%></p>
                                                <button class="button is-black is-outlined is-fullwidth">Contact Me</button>
                                            </div>
                                            
                                        </div>

                                        <!-- Buyer Profile -->
                                        <div class="column f-15">
                                             <article class="media">
                                                <div class="media-content">
                                                    <i class="fas fa-user m-r-5"></i>    Member Since: 
                                                </div>
                                                <div class="media-right">
                                                    <%= @request.user.created_at.strftime('%b %Y') %>
                                                </div>
                                            </article>
                                            <hr>
                                            <article class="media">
                                                <div class="media-content">
                                                    <i class="fas fa-user m-r-5"></i>From: 
                                                </div>
                                                <div class="media-right">
                                                    <%= @request.user.from %>
                                                </div>
                                            </article>
                                            <hr>
                                            <article class="media">
                                                <div class="media-content">
                                                    <i class="fas fa-user m-r-5"></i>About: 
                                                </div>
                                                <div class="media-right">
                                                    <%= @request.user.about %>
                                                </div>
                                            </article>
                                    </div>
                                </div>

                                    
                            </div>
                        </div>
                    </div>
                    
                </div>
            </div>

            <!-- RIGHT SIDE -->
            <div class="column">
               
                <hr class="h-10">
                
                <!-- From -->
                <article>
                    <div class="media">
                        <div class="media-content">From</div>
                        <div class="media-right">
                        <strong><%= @request.user.from %></strong> 
                        </div>
                    </div>
                </article>                                
                <hr class="h-10">
            </div>

        </div>
    </div>
</section>